<?php

/**
 * View file for gii generator.
 *
 * @var \ymaker\email\templates\gii\Generator
 *
 * @author Vladimir Kuprienko <vldmr.kuprienko@gmail.com>
 *
 * @since 1.1
 */
$className = $generator->migrationName;
echo "<?php\n";
?>

use yii\db\Migration;
use ymaker\email\templates\entities\EmailTemplate;

/**
 * Handles creating of email template.
 *
 * Generated by `yiimaker/yii2-email-templates`.
 * @see <?php echo \ymaker\email\templates\Module::getRepoUrl(); ?>

 */
class <?php echo $className; ?> extends Migration
{
    /**
     * Migration table name.
     *
     * @var string
     */
    public $tableName = '{{%email_template}}';
    /**
     * Migration table name.
     *
     * @var string
     */
    public $translationTableName = '{{%email_template_translation}}';


    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->insert($this->tableName, [
            'key' => '<?php echo $generator->key; ?>',
        ]);

        $templateId = EmailTemplate::find()
            ->select('id')
            ->where(['key' => '<?php echo $generator->key; ?>'])
            ->scalar();

<?php if (Yii::$app->getModule('email-templates')): ?>
        $this->batchInsert(
            $this->translationTableName,
            [
                'templateId',
                'language',
                'subject',
                'body',
                'hint',
            ],
            [
            <?php foreach (\motion\i18n\helpers\LanguageHelper::getInstance()->getLocales() as $language): ?>    [
                    'templateId'    => $templateId,
                    'language'      => '<?php echo $language; ?>',
                    'subject'       => '<?php echo $generator->subject; ?>',
                    'body'          => '<?php echo $generator->body; ?>',
                    'hint'          => '<?php echo $generator->hint; ?>',
                ],
            <?php endforeach; ?>]
        );
<?php else: ?>
        $this->insert($this->translationTableName, [
            'templateId'    => $templateId,
            'language'      => Yii::$app->language,
            'subject'       => '<?php echo $generator->subject; ?>',
            'body'          => '<?php echo $generator->body; ?>',
            'hint'          => '<?php echo $generator->hint; ?>',
        ]);
<?php endif; ?>
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->delete($this->tableName, '[[key]] = :key', [
            ':key' => '<?php echo $generator->key; ?>',
        ]);
    }
}
