<?php

/**
 * View file for gii generator.
 *
 * @var \ymaker\email\templates\gii\Generator
 *
 * @author Vladimir Kuprienko <vldmr.kuprienko@gmail.com>
 *
 * @since 1.1
 */
$className = $generator->migrationName;
echo "<?php\n";
?>

use yii\db\Migration;
use ymaker\email\templates\entities\EmailTemplate;

/**
 * Handles creating of email template.
 *
 * Generated by `yiimaker/yii2-email-templates`.

 */
class <?php echo $className; ?> extends Migration
{
    /**
     * Migration table name.
     *
     * @var string
     */
    public $tableName = '{{%email_template}}';
    /**
     * Migration table name.
     *
     * @var string
     */
    public $translationTableName = '{{%email_template_translation}}';


    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->insert($this->tableName, [
            'key' => '<?php echo $generator->key; ?>',
        ]);

        $templateId = EmailTemplate::find()
            ->select('id')
            ->where(['key' => '<?php echo $generator->key; ?>'])
            ->scalar();

        $this->insert($this->translationTableName, [
            'templateId'    => $templateId,
            'language'      => Yii::$app->language,
            'subject'       => '<?php echo $generator->subject; ?>',
            'body'          => '<?php echo $generator->body; ?>',
            'hint'          => '<?php echo $generator->hint; ?>',
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->delete($this->tableName, '[[key]] = :key', [
            ':key' => '<?php echo $generator->key; ?>',
        ]);
    }
}
